version: '3.10'
services:
  api:
    build: .
    command: hypercorn -b 0.0.0.0:8000 main:app
    restart: always
    # volumes:
    #   - .:/app
    ports:
      - "5151:8000"
    depends_on:
      - db
volumes:
  db-data:
